#include "config.h"
#include <cstdint>

uint32_t MAX_GAP = 0;
uint32_t MAX_GAP_PENALTY = 4;
double MAX_GAP_PENALTY_EXPONENT = 2.0;

uint32_t MAX_DAY_LENGTH = 5;
uint32_t MAX_DAY_LENGTH_PENALTY = 4;
double MAX_DAY_LENGTH_PENALTY_EXPONENT = 2.0;

uint32_t MIN_DAY_LENGTH = 2;
uint32_t MIN_DAY_LENGTH_PENALTY = 1;
double MIN_DAY_LENGTH_PENALTY_EXPONENT = 2.0;

uint32_t MAX_CONTINUOUS_CLASSES = 4;
uint32_t MAX_CONTINUOUS_CLASSES_PENALTY = 4;
double MAX_CONTINUOUS_CLASSES_PENALTY_EXPONENT = 2.0;

bool GUARANTEE_CROSS_CAMPUS_GAP = true;
uint32_t MULTI_CAMPUS_GAP = 1;

bool AVOID_RUSH_HOURS = true;
uint32_t AVOID_RUSH_HOUR_PENALTY = 8;

uint32_t ONLINE_PREFERENCE = 2;
uint32_t ONLINE_PREFERENCE_REWARD = 4;

uint32_t BALANCED_WEEK_DELTA = 2;
uint32_t BALANCED_WEEK_DELTA_REWARD = 3;

uint32_t PREFFERED_MIN_START = 10 * 3600;
uint32_t PREFFERED_MIN_START_REWARD = 4;

uint32_t PREFFERED_MAX_END = 15 * 3600;
uint32_t PREFFERED_MAX_END_REWARD = 3;

uint32_t DAY_OFF_REWARD = 7;